### ISSUE TITLE
flapping only working from ground

### ISSUE THREAD

**Issue by KDFireHero** [CammiePone/Icarus#70] opened 2023-11-19 00:36 UTC
if I run then jump to begin flying it works fine, but at anytime I'm flying and not flapping I can't start flapping without landing on the ground first to get a running head start

**Comment by KDFireHero** [comment] 2023-12-03 20:08
Recently found out the problem comes from Do A Barrel Roll

**Comment by UpcraftLP** [comment] 2024-04-13 22:46
duplicate of #42

**Closed as not planned by UpcraftLP** 2024-04-13 22:46 UTC
Labels: duplicate
