### ISSUE TITLE
[1.19.4] Creative inventory related crash

### ISSUE THREAD

**Issue by CryoNine** [CammiePone/Icarus#106] opened 2024-07-04 21:57 UTC
And this is on singleplayer so I'm also not sure why it says "server" 

Time: 2024-07-04 16:23:02
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class dev.cammiescorner.icarus.core.registry.ModItems$$Lambda$12559/0x0000000801952518 does not define or inherit an implementation of the resolved method 'abstract void accept(net.minecraft.class_1761$class_8128, net.minecraft.class_1761$class_7704)' of interface net.minecraft.class_1761$class_7914.
	at net.minecraft.class_1761.method_47306(class_1761.java:96)
	at net.minecraft.class_1761.polymer$getContentsWith(class_1761.java:2538)
	at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:39)
	at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:35)
	at eu.pb4.polymer.core.impl.networking.packets.PolymerItemGroupContent.of(PolymerItemGroupContent.java:24)
	at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.syncItemGroupContents(PolymerServerProtocol.java:239)
	at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.syncItemGroup(PolymerServerProtocol.java:224)
	at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.sendCreativeSyncPackets(PolymerServerProtocol.java:211)
	at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:151)
	at eu.pb4.polymer.core.impl.networking.PolymerServerProtocolHandler.lambda$handleSyncRequest$2(PolymerServerProtocolHandler.java:56)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:768)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6204382472 bytes (5916 MiB) / 16559112192 bytes (15792 MiB) up to 26809991168 bytes (25568 MiB)
	CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2684
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx25568m -Xms256m
	Fabric Mods: 
		ad_astra: Ad Astra 1.14.1
		ad_astra_giselle_addon: Ad Astra: Giselle Addon 3.4
		additionaladditions: Additional Additions 5.3.0
		additionallanterns: Additional Lanterns 1.1.1a
		additionalstructures: Additional Structures 4.1.2
		advanced-xray-fabric: Advanced XRay (Fabric) 1.19.4-1.4.0-build.15
		advancednetherite: Advanced Netherite 2.0.2-1.19.4
		alloy_forgery: Alloy Forgery 2.0.20+1.19.4
		alternate-current: Alternate Current 1.7.0
		amecs: Amecs 1.3.10+mc.1.19.4
			amecsapi: Amecs API 1.4.0+mc1.19.4
		amethyst_core: Amethyst Core 1.2.2+1.19.4
			common-protection-api: Common Protection API 1.0.0
		amethyst_imbuement: Amethyst Imbuement 1.19.4-06
			conditional-mixin: conditional mixin 0.3.2
			fzzy_config: Fzzy Config 0.1.1+1.19.3
			playerabilitylib: Pal 1.7.0
			structurized-reborn: Structurized Reborn 1.19.4-01
		anvil_fix: AnvilFix 19.0.2
		appleskin: AppleSkin 2.5.1+mc1.19.4
		architectury: Architectury 8.2.91
		ash: Ash API 1.0.4
		autoswitch: AutoSwitch 6.0.2
			autoswitch-api: AutoSwitch API 3.0.0
		autotools: AutoTools 2.0
		bambooeverything: Bamboo Everything 2.4.1-build.53+mc1.19.4
		bclib: BCLib 2.3.5
			wunderlib: WunderLib 1.0.1
		beaconoverhaul: Beacon Overhaul 1.7.7+1.19.4
			reach-entity-attributes: Reach Entity Attributes 2.3.2
		betterend: Better End 3.2.5
		betterf3: BetterF3 6.0.3
		betterfurnacesreforged: Better Furnaces Reforged 1.1.2
		bettermounthud: Better Mount HUD 1.2.1
		betternether: Better Nether 8.2.3
		betterthirdperson: Better Third Person 1.9.0
		biggerspongeabsorptionradius: Bigger Sponge Absorption Radius 3.1
		bitsandchisels: BitsAndChisels 2.7.1
			stacc: Stacc 1.5.2+boneless
		blockus: Blockus 2.6.9+1.19.4
		bobby: Bobby 4.0.6
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 18.0.6
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.6.1-1.19.4
			maelstrom_library: Maelstrom Library 1.5.1-1.19.4
			multipart_entities: MultipartEntities 1.4-1.19.4
		botarium: Botarium 2.0.5
		bridgingmod: Bridging Mod 2.3.0+1.19.4
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.1
		byg: Oh The Biomes You'll Go 4.0.1.1
		capes: Capes 1.5.3+1.19.4
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		carryon: Carry On 2.0.6.27
		chat_heads: Chat Heads 0.12.3
		cherishedworlds: Cherished Worlds 6.0.5+1.19.4
		chesttracker: Chest Tracker 1.1.21
			libgui: LibGui 7.0.0-beta.2+1.19.4
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
			whereisit: Where Is It 1.14.16
		clickthrough: ClickThrough 1.19.4-fabric0.76.0-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.19.4
		cloth-config: Cloth Config v10 10.1.117
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 10.0.0.4
		cmdkeybind: Command Macros 1.6.2-1.19.4
			kyrptconfig: Kyrpt Config 1.5.2-1.19.4
		collective: Collective 6.66
		colytra: Colytra 6.1.1+1.19.4
			spectrelib: SpectreLib 0.12.7+1.19.2
		compressedblocks: Compressed Blocks 1.5.0
		computercraft: CC: Tweaked 1.108.0
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
			io_netty_netty-codec-socks: netty-codec-socks 4.1.82.Final
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.82.Final
			org_squiddev_cobalt: Cobalt 0.7.3
		consistency_plus: Consistency Plus 0.5.2+RC.2+1.19.4
			stonecutter_recipe_tags: Stonecutter Recipe Tags 5.1.1+1.19.3.c283aa2.fabric
		controllable: Controllable 0.19.2
			io_github_libsdl4j_libsdl4j: libsdl4j 2.26.4-1.2
		controlling: Controlling For Fabric 11.1.5
		corgilib: CorgiLib 3.0.0.0
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		craftify: Craftify 1.16.0
			universalcraft: UniversalCraft 342
		cristellib: Cristel Lib 1.1.2
		customizableelytra: Customizable Elytra 1.6.6-1.19.4
		dark-enchanting: Dark Enchanting 1.0.1+1.19.4
			omega-config: OmegaConfig 1.2.3-1.18.1
		darkflight: DarkFlight - Simple Jetpack 1.0.4
		dawn: Dawn API 4.2.1
		dimdoors: DimensionalDoors 5.2.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			mm: Manningham Mills 2.3
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		doubledoors: Double Doors 5.0
		dragonloot: DragonLoot 1.1.4
		dramaticdoors: Dramatic Doors (Fabric) 1.19.4-2.0.1
		eatinganimationid: Eating Animation 1.9.3
		eldritch_mobs: EldritchMobs 1.14.0
			polymer-blocks: Polymer (Textured Blocks) 0.4.11+1.19.4
			polymer-core: Polymer (Core) 0.4.11+1.19.4
				polymer-networking: Polymer (Networking) 0.4.11+1.19.4
					polymer-common: Polymer (Common) 0.4.11+1.19.4
						packet_tweaker: Packet Tweaker 0.4.0+1.19.4
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.4.11+1.19.4
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
		elytraslot: Elytra Slot 6.2.1+1.19.4
		emeraldequipment: Emerald Equipment 1.0.7
		enchancement: Enchancement 1.19-21
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.8.1
		enchantedlib: Enchanted Lib 0.2.1
		enchantingcommands: Enchanting Commands 3.0
		enchantinginfuser: Enchanting Infuser 6.0.0
		enchdesc: EnchantmentDescriptions 15.0.3
		enderchests: EnderChests 1.1.7
		endrem: End Remastered 5.2.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.19.4
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 4.2.0+1.19.4
		enhancedmovement: Enhanced Movement 1.0.5
		entangled: Entangled 1.3.18
		essential: Essential 1.3.2.7+g7245995b31
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		essential-dependencies: Essential Dependencies 0
			elementa: Elementa 649
			vigilance: Vigilance 297
		expandedstorage: Expanded Storage 9.0.4
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.87.2+1.19.4
			fabric-api-base: Fabric API Base 0.4.28+737a6ee8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.29+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+6b242079f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.38+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.31+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.10+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.48+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.59+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.14+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+6d727b51f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.5.2+26f09d40f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.50+44c9c860f4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.17+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+4b6b93f0f4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.56+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.36+3f657af2f4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.21+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.10+8400c67ef4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.19+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.32+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.36+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.5+53c11dadf4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.44+10ce000ff4
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+3a1ea2f1f4
			fabric-models-v0: Fabric Models (v0) 0.4.1+a0255436f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.6+ae9c4c6af4
			fabric-networking-v0: Fabric Networking (v0) 0.3.46+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.1+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.13+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+95ae8716f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.2+90110d8df4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+90110d8df4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.42+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.32+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.25+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.45+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.5+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+8400c67ef4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.49+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.25+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+602c17c7f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.3.0+1b5f819af4
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabrication: Fabrication 3.4.14+1.19.4
			lib39-deferral: Lib39 (Deferral) 1.5.0-pre2.2+1.19.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		factory_api: Factory API 2.0
		fallingleaves: Falling Leaves 1.15.6
		fallingtree: FallingTree 3.13.1
		firespreadtweaks: Fire Spread Tweaks 2.3
		firstperson: FirstPerson 2.4.3
		followersteleporttoo: Followers Teleport Too 2.1
		forgeconfigapiport: Forge Config API Port 6.0.2
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		fzzy_core: Fzzy Core 0.2.7+1.19.4
		gamma_shifter: Gamma Shifter 1.0.1+mc1.19.4
		geckolib: Geckolib 4.2
			com_eliotlash_mclib_mclib: mclib 20
		geode_plus: Geode+ 1.1.9
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		geodes: More Geodes 1.7+1.19.4
		goblintraders: Goblin Traders 1.8.2
		growable_ores: Skniro's GrowableOres 1.2.2-1.19.4
			team_reborn_energy: Energy 3.0.0
		handcrafted: Handcrafted 2.2.0
		icarus: Icarus 1.15.1
		iceberg: Iceberg 1.1.9.1
		immersive_aircraft: Immersive Aircraft 0.7.9+1.19.4
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_armors: Immersive Armors 1.5.6+1.19.4
		indium: Indium 1.0.19+mc1.19.4
		inventorio: Inventorio 1.9.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 10.4.0
		jamlib: JamLib 0.6.1+1.19.4
		java: OpenJDK 64-Bit Server VM 17
		jeresources: Just Enough Resources 1.3.3.219
		lambdynlights: LambDynamicLights 2.3.1+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
		libipn: libIPN 3.0.2
		lightoverlay: Light Overlay 7.0.3
		litematica: Litematica 0.14.3
		malilib: MaLiLib 0.15.4
		mcwbridges: Macaw's Bridges 3.0.0
		mcwfences: Macaw's Fences and Walls 1.1.1
		mcwpaths: Macaw's Paths and Pavings 1.0.4
		mcwwindows: Macaw's Windows 2.2.1
		mes: Moog's End Structures 1.1-1.19.4-fabric
		midnightlib: MidnightLib 1.3.0
		minecraft: Minecraft 1.19.4
		mineralchance: Mineral Chance 3.2
		mishanguc: Mishang Urban Construction 1.2.7
		mixtape: Mixtape 1.5.0
		modmenu: Mod Menu 6.3.1
		moonlight: Moonlight 1.19.4-2.4.16
		more_chests: More Chests 2.0.0
		moremobvariants: More Mob Variants 1.2.0.1
		moretotems: More Totems 2.14.0
		mythicmetals: Mythic Metals 0.18.1+1.19.4
			additionalentityattributes: Additional Entity Attributes 1.2.2+1.19.4
		notenoughanimations: NotEnoughAnimations 1.7.4
		openblocks: Open Block Elevator Mod 0.0.3-1.19.4
		org_jetbrains_annotations: annotations 23.0.0
		owo: oωo 0.10.6+1.19.4
			blue_endless_jankson: jankson 1.2.2
		paintings: Paintings++ 10.4.0.0
		patchouli: Patchouli 1.19.4-79.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.5+1.14.4-1.20
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		philipsruins: Philip`s Ruins 1.19.4
		physicsmod: Physics Mod 2.12.5
		pigpen: PigPen 13.0.1
		pigsteel: Pigsteel Mod 1.8.3
		plushies: Plushie Mod 1.2.1
		polymorph: Polymorph 0.48.1+1.19.4
		puzzleslib: Puzzles Lib 6.0.11
		quarryplus: QuarryPlus 19.4.0
		randomsheepcolours: Random Sheep Colours 3.1
		reacharound: Reacharound 1.3.0
		reborncore: Reborn Core 5.7.0
		redstonepen: Redstone Pen 1.4.23
		reeses-sodium-options: Reese's Sodium Options 1.6.3+mc1.19.4-build.90
		replaymod: Replay Mod 1.19.4-2.6.13
		repurposed_structures: Repurposed Structures 6.3.25+1.19.4-fabric
		resourcefulconfig: Resourcefulconfig 1.2.0
		resourcefullib: Resourceful Lib 1.3.6
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 11.1.717
			error_notifier: Error Notifier 1.0.9
		runelic: Runelic 16.1.5
		saplanting: Saplanting 1.2.6
		searchables: Searchables 1.0.3
		sheepconsistency: Sheep Consistency 1.0.4
		shetiphiancore: ShetiPhianCore 1.3.12
		shulkerboxtooltip: Shulker Box Tooltip 3.4.4+1.19.4
		simplemagnets: Simple Magnets 1.1.11
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		somanyenchantments: So Many Enchantments Mod 0.3.1
		spawnermod: Enhanced Mob Spawners 1.2.4
		spongesucc: SpongeSucc (Lava Sponge) 1.0.0-1.19.4
		stacker: Stacker 3.1.0-1.19.4
		stackrefill: Stack Refill 4.0
		super_ore_block: Super Ore Block 2.0.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		survivalplus: SurvivalPlus 0.1.7b
		tawct: Time & Wind Custom Ticker 1.4.7+1.19.4
		techreborn: Tech Reborn 5.7.0
		terrablender: TerraBlender 2.2.0.154
		terrestria: Terrestria 5.2.7
			biolith: Biolith 0.0.1-alpha.4
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 6.1.3
			terraform-config-api-v1: Terraform Config API (v1) 6.1.3
			terraform-dirt-api-v1: Terraform Dirt API (v1) 6.1.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 6.1.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 6.1.3
			terraform-tree-api-v1: Terraform Tree API (v1) 6.1.3
			terraform-wood-api-v1: Terraform Wood API (v1) 6.1.3
		terrestria-client: Terrestria: Client 5.2.7
		terrestria-common: Terrestria: Common 5.2.7
		terrestria-worldgen: Terrestria: World Generation 5.2.7
		the_bumblezone: The Bumblezone - Fabric 6.7.21+1.19.4-fabric
			fake-player-api: Fake Player API 0.6.0
			noindium: No Indium? 1.1.0+1.19.4
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.0+1.19.4
		toms_storage: Tom's Simple Storage Mod 1.5.11
		toolstats: ToolStats 14.1.7
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		tradingpost: Trading Post 6.0.0
		transparent: Transparent 6.1.3
		trinkets: Trinkets 3.6.0
		universal_ores: Universal Ores 1.5.1
		upgradedshulkers: Upgraded Shulkers 1.1.3-1.19.4
			shulkerutils: shulkerutils 1.0.4-1.19
		usefulslime: Useful Slime 1.4.2
		utilitybelt: Utility Belt 1.3.3+1.19.4
			tutorial-lib: Tutorial Lib 1.1.2+1.19.4
		veinmining: Vein Mining 1.1.3+1.19.4
		villagersrespawn: Villagers Respawn 7
		visuality: Visuality 0.7.0
		visualworkbench: Visual Workbench 6.0.1
		wandering_collector: Wandering Collector 1.2.1+mc1.19.4
			coat: Coat 1.0.0-beta.20+mc1.19.4
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.19.4
			tweed4_base: tweed4_base 1.7.1+mc1.19.4
			tweed4_data: tweed4_data 1.2.1+mc1.19.4
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.19.4
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.19.4
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.19.4
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.19.4
		wands: Building Wands 2.6.9-release
		waveycapes: WaveyCapes 1.4.7
		windchimes: Windchimes 1.2.2
		wirelesschargers: Wireless Chargers 1.0.9+a
		wirelessredstone: Wireless Redstone 1.19.4-1.1.0
		wooltweaks: Wool Tweaks 3.1
		worldedit: WorldEdit 7.2.14+6360-094b734
		wormhole: Wormhole (Portals) 1.1.16
		xaerominimap: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
		xps: Xp Obelisk 0.4.9-r+1.19.4-Fabric
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.1+1.19.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			yet_another_config_lib: YetAnotherConfigLib 2.5.1+1.19.4
		yigd: You're in Grave Danger 1.6.0
		zoomify: Zoomify 2.9.4
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Loaded Shaderpack: ComplementaryReimagined_r2.3
		Profile: Custom (+95 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['iPOTAT00'/432, l='ServerLevel[This is honestly]', x=-9967.15, y=53.00, z=-1568.91]]
	Data Packs: vanilla, fabric, dimdoors:default, dimdoors:classic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.11-1.19.4

**Comment by CryoNine** [comment] 2024-07-05 02:22
This doesn't happen when I open my inventory, it happens right as the world starts to load

**Comment by UpcraftLP** [comment] 2024-07-05 03:53
It's a crash caused by the creative inventory (even with no other mods installed), it just so happens that one of your mods touches that a bit earlier than when I tested with just icarus alone.

**Comment by UpcraftLP** [comment] 2024-07-07 02:40
fixed in https://github.com/Up-Mods/Icarus/commit/0ea951136363980f3e582849dd9b018d7107f2e0 / Icarus 1.15.2

**Closed as completed by UpcraftLP** 2024-07-07 02:40 UTC
