### ISSUE TITLE
Issue with flying

### ISSUE THREAD

**Issue by BloodKneight** [CammiePone/Icarus#73] opened 2023-12-10 04:13 UTC
I was able fly without issues now it this weird slow flight almost like a gliding flight. I can only fly in loops, difficult get off ground, or make any hard turn. I also can't slow down and it impossible to land? I this a toggle that I can turn off.

**Comment by JedGITH** [comment] 2024-02-13 06:59
Check your mod pack, and remove the mod 'do a barrel roll,' this mod changes the normal elytra flight to a more 'realistic' feel, removing it fixes the gliding issue.

**Comment by UpcraftLP** [comment] 2024-04-13 22:44
duplicate of #42

**Closed as not planned by UpcraftLP** 2024-04-13 22:44 UTC
Labels: duplicate
