### ISSUE TITLE
Confused by how the flying should be and how to fix it

### ISSUE THREAD

**Issue by NyxLeviathanWoods** [CammiePone/Icarus#72] opened 2023-11-29 14:17 UTC
For about a month now, some friends and I have been playing on a server together using the Prominence 2 modpack which has the Icarus mod in it. I had crafted myself wings once i found i could and ran across a confusing occurrence. 

At first, the flying was easy to use, double space and looking upwards to fly up into the sky before using my cursor to determine my direction and only needing to hold w to keep going forward. Made it easy to do a lot of things around the server.

Then, after i logged back in after simply logging off to get some dinner, the flying changed. I couldn't take flight, i'd just glide into the ground, and if i jumped off at a certain height to fly, my cursor would not work into direction but instead cause me to spin, go upside down, and what not. the only thing providing any direction was using a and d only slightly, as even using those buttons would also result in spinning if i held them for too long.

after trying to mention it to my techy friend, who sadly could never get back to me due to some bad stuff occurring in their life. I just left it as somethings just restarting the launch of the pack would fix it to the formerly mentioned version of flying.

however, thats no longer working for me now and I am stuck with the latter, which i can't use at all. so I come her with the question of which of the 2 is meant to be how these wings work, and if its the first method i mentioned, then what should be done to fix this issue?

**Comment by NyxLeviathanWoods** [comment] 2023-11-29 14:23
I also apologize if this was an issue already brought up before. If any other details are needed, I'll try to provide them the best i can.

**Comment by CammiePone** [comment] 2023-11-29 14:30
tbh im really not sure, because ive never been able to replicate this problem

**Comment by NyxLeviathanWoods** [comment] 2023-11-29 15:45
well.... uh... crap XD

**Comment by JedGITH** [comment] 2024-02-13 06:59
Check your mod pack, and remove the mod 'do a barrel roll,' this mod changes the normal elytra flight to a more 'realistic' feel, removing it fixes the gliding issue.

**Comment by UpcraftLP** [comment] 2024-04-13 22:44
duplicate of #42

**Closed as completed** 2024-04-13 22:43 UTC
Labels: duplicate
