### ISSUE TITLE
Compatability Issue: Epic Fight Mod

### ISSUE THREAD

**Issue by Ph4i1ur3** [CammiePone/Icarus#97] opened 2024-05-20 14:08 UTC
[crash-2024-05-20_09.52.26-client.txt](https://github.com/Up-Mods/Icarus/files/15377992/crash-2024-05-20_09.52.26-client.txt)

Icarus seems to be incompatible with Epic Fight mod on Forge 1.20.1

I removed mods in a separate game instance until the conflict occurred

**Comment by UpcraftLP** [comment] 2024-05-20 14:19
Duplicate of #94

**Closed as not planned by UpcraftLP** 2024-05-20 14:19 UTC
Labels: duplicate
