### ISSUE TITLE
Cannot fly, not even glide anymore

### ISSUE THREAD

**Issue by ShieldMaidenVal** [CammiePone/Icarus#51] opened 2023-04-08 20:58 UTC
I'm not sure what changed at all in my SP world, nothing added or options for Icarus changed save for the durability of them, and now back to the title. Any solutions? I'm rather attached to my wings!

**Comment by CammiePone** [comment] 2023-04-08 20:59
duplicate of #42. please check issues before making new ones

**Closed as completed by CammiePone** 2023-04-08 20:59 UTC

**Comment by ShieldMaidenVal** [comment] 2023-04-08 21:40
It's not a duplicate, as I cannot even glide at all either. I have zero functionality from the mod.
